[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet] #or [program.devnet]
anchor_vault = "7FKukPs1rAnQ9yDsJAshbvjAunc2wJVLb8zp3SsFcs23" #Program ID

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet" #or "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
