[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dp_test_cpi = "2r9AvbDhiTq9dcAojVmJgnxZX3AH7nsycL6WXtPPqNW4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nathan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
